spring:
#  数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vue_shop?useUnicode=true&characterEncoding=UTF-8
    password: 123456
    username: root
#  热部署配置
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效

mybatis:
#  配置mapper文件位置
  mapperLocations: classpath:mapping/*.xml
  type-aliases-package: com.hwh.entity

# pagehelper分页插件相关配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql